name: Server CI - run e2e test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["none"]

jobs:
  lint:
    name: check-lint

    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Notify Slack if error exists
        if: ${{ failure() }}
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#ci'

      - name: Block merge if error exists
        if: ${{ failure() }}
        run: |
          echo "Lint error found!!"
          echo "Please fix them before merging."
          exit 1
